export const siteConfig = {
  name: "Soufian Elouazzani - DevOps / Software Engineer",
  authorName: "Soufian Elouazzani",
  username: "soufian-elouazzani",
  description:
    "Soufian Elouazzani — DevOps & Software Engineer at INPT Rabat. I build applications end-to-end: from React and FastAPI services to Docker, Kubernetes, Terraform, and GitHub Actions CI/CD. Explore my projects, internships, and open-source work.",
  url: "https://profolio-website11.vercel.app",
  links: {
    twitter: "https://x.com/soufian-elouazzani",
    github: "https://github.com/soufian-elouazzani",
    /** Repo used for the header star count badge */
    githubStarRepo: "https://github.com/soufian-elouazzani/chat-app-infra",
  },
  ogImage: "/logo.png",
  iconIco: "/favicon.ico",
  logoIcon: "/logo.png",
  keywords: [
    "Soufian Elouazzani",
    "DevOps Engineer",
    "CI/CD",
    "Jenkins",
    "GitLab",
    "GitHub Actions",
    "Terraform",
    "Ansible",
    "AWS",
    "Docker",
    "Kubernetes",
    "SRE",
    "Site Reliability Engineer",
    "Infrastructure as Code",
    "Cloud Architecture",
    "Linux",
    "Automation Engineer",
    "Software Development",
    "Next.js Developer",
    "TypeScript",
  ],
};
