export const siteConfig = {
  name: "Soufian Elouazzani — Freelance Web Developer & Digital Solutions Consultant",
  authorName: "Soufian Elouazzani",
  username: "soufian-elouazzani",
  description:
    "Soufian Elouazzani — freelance web developer and digital solutions consultant. I build business websites, e-commerce stores, and AI-powered tools for salons, restaurants, shops, and small businesses. Explore live demos and engineering projects.",
  url: "https://soufian.engineer",
  links: {
    twitter: "https://x.com/soufian-elouazzani",
    github: "https://github.com/soufian-elouazzani",
  },
  ogImage: "/logo.png",
  iconIco: "/favicon.ico",
  logoIcon: "/logo.png",
  keywords: [
    "Soufian Elouazzani",
    "Freelance Web Developer",
    "Website Consultant",
    "Digital Solutions",
    "Business Website",
    "E-commerce Developer",
    "AI Receptionist",
    "DevOps Engineer",
    "Full Stack Developer",
    "Next.js Developer",
    "TypeScript",
    "React",
    "Small Business Websites",
  ],
};
