export const siteConfig = {
  name: "Soufian Elouazzani - DevOps Engineer",
  authorName: "Soufian Elouazzani",
  username: "soufian-elouazzani",
  description:
    "Soufian Elouazzani - DevOps Engineer working at the intersection of automated CI/CD pipelines, Infrastructure as Code, scalable systems, and cloud architecture. Explore my projects, experience, and contributions.",
  url: "https://profolio-website11.vercel.app",
  links: {
    twitter: "https://x.com/soufian-elouazzani",
    github: "https://github.com/soufian-elouazzani",
    templateRepo: "https://github.com/namanbarkiya/minimal-next-portfolio",
  },
  ogImage: "/logo.png",
  iconIco: "/favicon.ico",
  logoIcon: "/logo.png",
  keywords: [
    "Soufian Elouazzani",
    "DevOps Engineer",
    "CI/CD",
    "Jenkins",
    "GitLab",
    "GitHub Actions",
    "Terraform",
    "Ansible",
    "AWS",
    "Docker",
    "Kubernetes",
    "SRE",
    "Site Reliability Engineer",
    "Infrastructure as Code",
    "Cloud Architecture",
    "Linux",
    "Automation Engineer",
    "Software Development",
    "Next.js Developer",
    "TypeScript",
  ],
};
